# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Octicons Jekyll Include
description: >- # this means to ignore newlines until "baseurl:"
  An alternative way to include Octicons in your Jekyll site, fully compatible
  with GitHub Pages.
baseurl: "/octicons-jekyll-include" # the subpath of your site, e.g. /blog
url: "https://www.bengodfrey.net" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: BenJetson

# Build settings
livereload: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-readme-index

header_pages:
  - icons.html

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true

collections:
  octicons:
    output: true
    sort_by: icon_id

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _octicons
    values:
      layout: icon
      permalink: /icon/:name
  - scope:
      path: README.md
    values:
      layout: home

octicon_classes: null

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - scripts/
